### PR TITLE
Implemented nicer time output

### LINKED ISSUE #7: Nicer time display in `perf` tool
Current output of `python3 -m perf` -- introduced on `dev` branch in 5ecf178 -- looks like this:
```pycon
Game time for policy 'None' over 100 games:
╭─────────────┬─────────────┬─────────────┬─────────────┬────────────╮
│ Num players │        Mean │         Std │         Min │        Max │
├─────────────┼─────────────┼─────────────┼─────────────┼────────────┤
│           2 │ 0.000787851 │ 4.55363e-05 │ 0.000712454 │ 0.0010466  │
│           3 │ 0.000864026 │ 6.41655e-05 │ 0.000753319 │ 0.00101083 │
│           4 │ 0.00106616  │ 3.5839e-05  │ 0.000989834 │ 0.00114714 │
│           5 │ 0.00102049  │ 8.67554e-05 │ 0.000913194 │ 0.00138938 │
╰─────────────┴─────────────┴─────────────┴─────────────┴────────────╯
```

It would be nicer to have
```pycon
╭─────────────┬────────┬────────┬───────┬────────╮
│ Num players │   Mean │    Std │   Min │    Max │
├─────────────┼────────┼────────┼───────┼────────┤
│           2 │  788us │ 45.5us │ 712us │ 1.05ms │
│           3 │  864us │ 64.2us │ 753us │ 1.01ms │
│           4 │ 1.07ms │ 35.8us │ 990us │ 1.15ms │
│           5 │ 1.02ms │ 86.7us │ 913us │ 1.39ms │
╰─────────────┴────────┴────────┴───────┴────────╯
```

### To close issue

Implement `format_time(t: float) -> str` from `/perf/__init__.py`.

More specifically:
- Number is displayed on at most 4 characters,
- Time units can be `"ns", "us", "ms", "ss", "mn", "hr", "dd", "mm", "yy"`, though nothing higher than seconds -- `"ss"` -- should be used in practise here.

### Following non triviality needs ruling

Should the value `0.9995` be mapped to `"999ms"` or `"1.00ss"`? The latter seems more natural, but precision is lowered to `10ms`.

Open for discussion.

### PR DESCRIPTION
**Pull request by csongorpilinszkinagy**
Fixes #7

Implemented nicer time output up to 999 seconds with the possibility of just returning raw ndarray data.
Please let me know if my coding style is not up to par.

### CODE REVIEW

**Comment by eliegoudout** [comment]
Hello !
Thank you **very much** for contributing :) I started testing/reviewing your code offline but I might need a bit more time to get back to your PR with a complete review. A few points I can already mention to help you doing PRs:
- It is often a good idea to use [flake8](https://pypi.org/project/flake8/) on you code. It is a tool to help people format their code to certain standards. It shows users where the code isn't compliant to standard rules. There is also [black](https://pypi.org/project/black/) which can directly modify your code format, but I won't use it in this project atm. To use `flake8`, install it (_e.g._ `python3 -m pip install flake8`) and from root directory of the project, simply type `flake8 .`.
- The function `main` should now return `list[_Timestat] | None` (type hinting),
- Your function seems to have a "1-off" behaviour:
```pycon
>>> format_time(1)
'999ss'
```

Thanks again for contributing, I will get back to you later!

Cheers.

**Comment by csongorpilinszkinagy** [comment]
Ok, that does not look good, I might need an entirely new approach. Sorry for not testing thoroughly, maybe I should start with the testing issue and then come back to finish this. What would be your priority?

Thanks for the style guide regardless!

**Comment by eliegoudout** [comment]
Don't worry, this task seems very easy but can hide a lot of subtle cases. I discovered even more now: let's say last unit we use is `'ns'`, then under `1ns`, we might want to display for example `0.04ns` instead of `0.00ns` which is the only case where we authorize a leading zero.

Don't worry about the test issue, I assigned this one to myself since I already started doing it!

Thanks though :)
Have fun

**Comment by eliegoudout** [comment]
Feature was implemented, see my [closing comment](https://github.com/eliegoudout/lasvegas/issues/7#issuecomment-1464869475) on the issue.

Thanks for contributing!
> 
> ## 🙏 Contributors 🙏
> 
> Élie Goudout, Csongor Pilinszki-Nagy.

**Pull request closed without merging**
